### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zgerrard** [palkerecsenyi/firestore-serializers#4]
https://github.com/palkerecsenyi/firestore-serializers/blob/2daea9b54487e0f57735c1aaeceb9502bf295367/src/Deserialize.ts#L73

Hi, I think there might be a bug in here: shouldn't it be `firestore` instead of `firebase.firestore()`?

**Comment by zgerrard** [comment]
Verified that this is indeed a bug. The library does not work without this fix and throws a firebaseApp initialization error.

**Comment by palkerecsenyi** [comment]
I've made substantial modifications to the whole project just now so that it supports Firebase v9 — I'll close the issue for now, but please feel free to re-open if it's still not working. Thanks!
